### ISSUE TITLE
Question sur l'application C#

### ISSUE THREAD

**Issue by vic1997** [vic1997/projet-slam-web#4]
J'ai quelques questions, dites moi tout : 

- Qu'est ce que l'application affichera comme donnée ?
- Qu'est ce que l'application modifiera comme donnée ?
- Faut-il se connecter à son compte via l'application pour pouvoir l'utiliser ?

Car l'application permettra de gérer beaucoup de choses, si quelqu'un qui n'a normalement pas les droits possède cette application, il pourrait faire n'importe quoi et sans compte.

Je vous laisse répondre @RiTi97 @TSO68 !

**Comment by RiTi97** [comment]
L'application affichera un menu ou l'on pourra sélectionner tout d'abord l'action que l'on souhaite réaliser ajout/modification/suppression... et ensuite proposera les tables à modifier.
L'appli permettra de gérer les produits, membres du personnel, matchs, comptes utilisateurs notamment.
Il serait en effet préférable d'appliquer des droits aux utilisateurs afin de gérer la base de données, mais ça n'est pas la chose à faire en priorité, il faut tout d'abord que l'on s'assure d'avoir une application effective pour l'examen.

**Comment by vic1997** [comment]
Ok, je ferais des maquettes pour vous montrer comment je pense faire l'application. Il faudra me dire si ça vous convient et si ça respecte ce qu'on veut mettre en place.
[Maquette de l'application graphique](https://github.com/vic1997/projet-slam-web/projects/1#card-3003997)

**Comment by TSO68** [comment]
Une gestion des droits modifierait la base de données, en créant un droit admin pour les comptes dans la table actuelle pour prendre le plus simple. Mais oui, ce n'est pas une priorité pour l'instant,

Pour le reste @RiTi97 a tout dit.

**Comment by vic1997** [comment]
J'ai fais une maquette, dites ce qu'il faut changer, supprimer, ajouter dans les menus. Pour les détails c'est normal, je voulais pas ajouter plein de Forms alors que ça servait à rien.

- [ ] Menu Configuration : Utilisateur
- [ ] Menu Actions : Trouver, Ajouter, Modifier, Supprimer

**Comment by vic1997** [comment]
J'ai oublié de mettre la maquette : http://i.imgur.com/LwCx4rG.gif

**Comment by TSO68** [comment]
Je dirai que c'est bon.

Il faudra juste savoir à quels comptes on lie la partie Configuration.

**Comment by vic1997** [comment]
@TSO68 Oui, j'ai pensé à utiliser les comptes MySQL, ça éviterais de devoir créer une table exprès pour ça. Après je sais pas si c'est super sécurisé ça.

**Comment by vic1997** [comment]
Étant donné qu'on est repartit en arrière pour développer une application plus simple et plus optimisé. Cette question ne sert plus à rien, je ferme donc !
