### ISSUE TITLE
Comment récupérer le poste d'un joueur ?

### ISSUE THREAD

**Issue by vic1997** [vic1997/projet-slam-web#5]
Depuis la classe Joueur, comment récupérer le poste d'un joueur ?

[Le code](https://pastebin.com/5YNwZcBf)

Je pense que la fonction pour récupérer le poste du joueur est faux, dites moi ce qu'il faut modifier.

**Comment by TSO68** [comment]
T'as pas oublié de déclarer lePoste dans le constructeur genre this.lePoste = lePoste ? Et ça permet à ta fonction de marcher ?

Je dis ça mais je sais pas si c'est pareil en C# qu'en java...

**Comment by vic1997** [comment]
@Tso68 si justement, je crois que c'est ça mais j'étais pas sur et j'ai pas essayé. Je test ça dès que je peux et je vous dis si ça marche.

**Comment by vic1997** [comment]
Corrigé.
