### ISSUE TITLE
Besoin d'aide sur les classes

### ISSUE THREAD

**Issue by vic1997** [vic1997/projet-slam-web#6]
Faut-il faire ces classes ?
[http://i.imgur.com/U55mcFR.png](http://i.imgur.com/U55mcFR.png)

**Comment by TSO68** [comment]
ligneCmd :
Oui. Normalement, c'est même une agrégation depuis Commande (si on supprime une commande, ça supprime les lignes de la commande).


fait :
Je dirai non. Je pense que la classe Produit aura une ArrayList de Taille mais sans être sûr.

participe : 
Je pense que oui.
